[tool.briefcase]
project_name = "Face Recognition Attendance"
bundle = "com.yourcompany.attendance"
version = "0.1.0"
url = "https://yourcompany.com/attendance"
license = "BSD license"
author = 'Your Name'
author_email = "your.email@example.com"

[tool.briefcase.app.attendance]
formal_name = "Face Recognition Attendance"
description = "A face recognition based attendance system"
icon = ["Icon.ico"]
sources = ['src']
requires = [
    "dlib",
    "face_recognition",
    "flask",
    "opencv-python",
    "numpy",
    "pandas"
]

[tool.briefcase.app.attendance.windows]
requires = []